In [5]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/SuperStoreOrders.csv")

In [26]:
df.head(10)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011
5,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",55,2,0.1,15.342,1.80,Medium,2011
6,CA-2011-1510,2/1/2011,6/1/2011,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,...,Technology,Machines,"Okidata Inkjet, Wireless",314,1,0.0,3.120,24.10,Medium,2011
7,IN-2011-79397,3/1/2011,3/1/2011,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Appliances,"Hoover Microwave, White",276,1,0.1,110.412,125.32,Critical,2011
8,ID-2011-80230,3/1/2011,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Technology,Copiers,"Hewlett Wireless Fax, Laser",912,4,0.4,-319.464,107.10,Low,2011
9,IZ-2011-4680,3/1/2011,7/1/2011,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Furniture,Chairs,"Novimex Swivel Stool, Set of Two",667,4,0.0,253.320,81.26,High,2011

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  str
 1   order_date      51290 non-null  str
 2   ship_date       51290 non-null  str
 3   ship_mode       51290 non-null  str
 4   customer_name   51290 non-null  str
 5   segment         51290 non-null  str
 6   state           51290 non-null  str
 7   country         51290 non-null  str
 8   market          51290 non-null  str
 9   region          51290 non-null  str
 10  product_id      51290 non-null  str
 11  category        51290 non-null  str
 12  sub_category    51290 non-null  str
 13  product_name    51290 non-null  str
 14  sales           51290 non-null  str
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  str
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), str(16)
memory usage: 8.2 MB

In [28]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='str')

In [29]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [30]:
df['category'].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [33]:
df['region'].value_counts()

region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

In [35]:
df.shape

(51290, 21)

In [37]:
df.dtypes

order_id              str
order_date            str
ship_date             str
ship_mode             str
customer_name         str
segment               str
state                 str
country               str
market                str
region                str
product_id            str
category              str
sub_category          str
product_name          str
sales                 str
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority        str
year                int64
dtype: object

In [47]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    format='mixed',
    dayfirst=True
)

df['ship_date'] = pd.to_datetime(
    df['ship_date'],
    format='mixed',
    dayfirst=True
)

In [49]:
df[['order_date', 'ship_date']].head()

  order_date  ship_date
0 2011-01-01 2011-01-06
1 2011-01-01 2011-01-08
2 2011-01-01 2011-01-05
3 2011-01-01 2011-01-05
4 2011-01-01 2011-01-08

In [50]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_month_name'] = df['order_date'].dt.month_name()

In [54]:
df[['order_date', 'order_year', 'order_month', 'order_month_name']].head()

  order_date  order_year  order_month order_month_name
0 2011-01-01        2011            1          January
1 2011-01-01        2011            1          January
2 2011-01-01        2011            1          January
3 2011-01-01        2011            1          January
4 2011-01-01        2011            1          January

In [63]:
df['sales'] = pd.to_numeric(
    df['sales'].astype(str).str.replace(',', ''),
    errors='coerce'
)

In [65]:
df['sales'].dtype

dtype('int64')

In [67]:
df.groupby('category')['sales'].mean().sort_values(ascending=False)

category
Technology         467.872103
Furniture          416.249899
Office Supplies    121.105426
Name: sales, dtype: float64

In [68]:
df.groupby('category')['profit'].mean().sort_values(ascending=False)

category
Technology         65.454958
Furniture          29.038300
Office Supplies    16.578961
Name: profit, dtype: float64

In [69]:
df.groupby('region')['sales'].sum().sort_values(ascending=False)

region
Central           2822399
South             1600960
North             1248192
Oceania           1100207
Southeast Asia     884438
North Asia         848349
EMEA               806184
Africa             783776
Central Asia       752839
West               725514
East               678834
Caribbean          324281
Canada              66932
Name: sales, dtype: int64

In [71]:
df.groupby('region')['profit'].sum().sort_values(ascending=False)

region
Central           311403.98164
North             194597.95252
North Asia        165578.42100
South             140355.76618
Central Asia      132480.18700
Oceania           121666.64200
West              108418.44890
East               91522.78000
Africa             88871.63100
EMEA               43897.97100
Caribbean          34571.32104
Southeast Asia     17852.32900
Canada             17817.39000
Name: profit, dtype: float64

In [73]:
df.groupby('discount')['profit'].mean().sort_values()

discount
0.850   -1534.329000
0.570    -526.129000
0.650    -365.997971
0.550    -315.067200
0.602    -213.279085
0.800    -122.203244
0.350    -116.144693
0.402    -109.908138
0.700    -104.339576
0.500     -97.140158
0.320     -88.560656
0.600     -81.732147
0.370     -78.462191
0.300     -57.899557
0.400     -45.246603
0.470     -42.982420
0.450     -41.610973
0.202     -14.518847
0.270      -4.317213
0.250       4.043371
0.200      23.552594
0.170      38.317107
0.150      50.602409
0.000      61.039514
0.100      64.071216
0.002     125.762649
0.070     140.990022
Name: profit, dtype: float64

In [75]:
df.groupby('category')['discount'].mean()

category
Furniture          0.168087
Office Supplies    0.137409
Technology         0.135342
Name: discount, dtype: float64

In [76]:
df.groupby('category')['shipping_cost'].mean().sort_values(ascending=False)

category
Technology         49.999876
Furniture          44.584919
Office Supplies    12.964899
Name: shipping_cost, dtype: float64

In [78]:
df.groupby('category')['quantity'].mean().sort_values(ascending=False)

category
Furniture          3.539287
Technology         3.468691
Office Supplies    3.459278
Name: quantity, dtype: float64

In [80]:
df.groupby('category')['discount'].describe()

                   count      mean       std  min  25%  50%   75%   max
category
Furniture         9876.0  0.168087  0.203003  0.0  0.0  0.1  0.27  0.85
Office Supplies  31273.0  0.137409  0.218518  0.0  0.0  0.0  0.20  0.80
Technology       10141.0  0.135342  0.199417  0.0  0.0  0.0  0.20  0.70

In [82]:
df[df['region'] == 'Southeast Asia'][['sales','profit','discount']].describe()

             sales       profit     discount
count  3129.000000  3129.000000  3129.000000
mean    282.658357     5.705442     0.272077
std     470.874794   133.840815     0.163167
min       3.000000 -1294.350300     0.000000
25%      41.000000   -20.632800     0.170000
50%     105.000000    -1.353300     0.270000
75%     313.000000    21.096000     0.450000
max    4242.000000  1554.432000     0.570000

In [83]:
df.groupby('order_year')['sales'].sum()

order_year
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: sales, dtype: int64

In [84]:
df.groupby('order_year')['profit'].sum()

order_year
2011    248940.81154
2012    307415.27910
2013    408512.76018
2014    504165.97046
Name: profit, dtype: float64

In [85]:
monthly_sales = df.groupby('order_month_name')['sales'].sum()
monthly_sales

order_month_name
April         698603
August       1293852
December     1580816
February      543768
January       675141
July          749423
June         1269751
March         770519
May           904061
November     1551319
October      1168220
September    1437432
Name: sales, dtype: int64

In [86]:
monthly_profit = df.groupby('order_month_name')['profit'].sum()
monthly_profit

order_month_name
April         73513.63124
August       151854.10972
December     170718.12710
February      72509.72922
January       73535.38454
July          78070.09172
June         147079.41684
March         94087.52096
May          104509.78428
November     175449.48412
October      157269.35838
September    170438.18316
Name: profit, dtype: float64

In [96]:
df['profit_margin'] = (df['profit'] / df['sales']) * 100
df['profit_margin'] = np.where(
    df['sales'] > 0,
    (df['profit'] / df['sales']) * 100,
    np.nan
)

In [97]:
df.groupby('category')['profit_margin'].mean().sort_values(ascending=False)

category
Office Supplies    5.855933
Technology         4.965838
Furniture          0.874818
Name: profit_margin, dtype: float64

In [99]:
df.groupby('region')['profit_margin'].mean().sort_values(ascending=False)

region
Canada            24.743089
West              21.944050
North Asia        17.951985
East              16.716939
Central Asia      14.698673
North             12.521579
Oceania            8.362353
Caribbean          8.118207
Central            6.009046
South              5.344237
Southeast Asia    -7.886966
EMEA             -14.161834
Africa           -14.509152
Name: profit_margin, dtype: float64

In [100]:
df[df['sales'] == 0]

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,quantity,discount,profit,shipping_cost,order_priority,year,order_year,order_month,order_month_name,profit_margin
40017,US-2014-102288,2014-06-20,2014-06-24,Standard Class,Zuschuss Carroll,Consumer,Texas,United States,US,Central,...,1,0.8,-1.11,0.01,Medium,2014,2014,6,June,NaN

In [101]:
df.groupby('region')['discount'].mean().sort_values(ascending=False)

region
Southeast Asia    0.272077
EMEA              0.196083
Africa            0.156704
Oceania           0.153169
South             0.149050
East              0.145365
Central           0.138851
Caribbean         0.135751
West              0.109335
North             0.096056
Central Asia      0.067480
North Asia        0.048717
Canada            0.000000
Name: discount, dtype: float64

In [102]:
df.groupby('region')['shipping_cost'].mean().sort_values(ascending=False)

region
North Asia        40.646112
Central Asia      38.003003
Oceania           34.593780
Southeast Asia    29.937948
North             27.476299
Central           26.710494
East              25.542001
South             25.353509
West              23.887687
Caribbean         21.059260
Canada            19.285495
Africa            19.215058
EMEA              17.573221
Name: shipping_cost, dtype: float64

In [103]:
pd.crosstab(df['region'], df['category'])

category        Furniture  Office Supplies  Technology
region
Africa                631             3045         911
Canada                 42              277          65
Caribbean             376              973         341
Central              2046             6936        2135
Central Asia          478             1111         459
EMEA                  770             3297         962
East                  601             1712         535
North                 945             2914         926
North Asia            522             1332         484
Oceania               742             1961         784
South                1329             4045        1271
Southeast Asia        687             1773         669
West                  707             1897         599

In [104]:
df.groupby(['region','category'])['profit'].mean().sort_values()

region          category
Southeast Asia  Furniture          -10.581902
                Office Supplies      2.353780
EMEA            Office Supplies      4.509976
East            Furniture            5.068496
Africa          Office Supplies      9.353055
EMEA            Furniture           14.979397
Caribbean       Office Supplies     15.229472
West            Furniture           16.272914
Caribbean       Furniture           16.551755
South           Office Supplies     16.686279
Oceania         Office Supplies     16.984287
South           Furniture           17.044114
Central         Office Supplies     17.490588
EMEA            Technology          18.185492
North           Office Supplies     22.101370
East            Office Supplies     23.957114
Central Asia    Office Supplies     24.396490
Africa          Furniture           25.771926
Central         Furniture           26.662190
West            Office Supplies     27.733183
Canada          Office Supplies     28.727545
North Asia      Office Supplies     30.725304
Southeast Asia  Technology          31.313668
North           Furniture           32.721765
South           Technology          39.502863
Caribbean       Technology          39.676202
Oceania         Furniture           45.318644
Africa          Technology          48.440717
Canada          Furniture           62.220000
Central         Technology          63.484038
Oceania         Technology          69.813804
West            Technology          73.962687
East            Technology          88.714084
North Asia      Furniture           99.964178
Central Asia    Furniture          102.375967
North           Technology         107.205714
Canada          Technology         111.486462
Central Asia    Technology         122.962908
North Asia      Technology         149.733502
Name: profit, dtype: float64

In [105]:
df[
    (df['region'] == 'Southeast Asia') &
    (df['category'] == 'Furniture')
][['sales','profit','discount']].describe()

             sales       profit    discount
count   687.000000   687.000000  687.000000
mean    456.173217   -10.581902    0.247147
std     545.493320   194.262112    0.129268
min      14.000000 -1294.350300    0.000000
25%     126.500000   -39.129750    0.250000
50%     261.000000     4.725900    0.270000
75%     564.000000    49.657650    0.270000
max    3707.000000  1554.432000    0.570000

In [106]:
df.groupby(['category'])['discount'].mean().sort_values(ascending=False)

category
Furniture          0.168087
Office Supplies    0.137409
Technology         0.135342
Name: discount, dtype: float64

In [107]:
df.groupby(['category'])['profit_margin'].mean().sort_values()

category
Furniture          0.874818
Technology         4.965838
Office Supplies    5.855933
Name: profit_margin, dtype: float64

In [108]:
df.groupby(['category','discount'])['profit'].mean().sort_values()

category         discount
Furniture        0.850      -1534.329000
                 0.570       -526.129000
                 0.800       -504.824125
Technology       0.650       -365.997971
Furniture        0.550       -315.067200
                 0.470       -314.125738
                 0.450       -276.638662
                 0.700       -272.108969
Technology       0.602       -213.279085
                 0.700       -208.525540
Furniture        0.500       -196.461967
Technology       0.500       -189.463419
                 0.600       -147.845323
Furniture        0.350       -137.047280
                 0.600       -130.900546
Technology       0.402       -109.908138
Furniture        0.370       -108.956376
Office Supplies  0.800       -101.796797
Furniture        0.320        -88.560656
Technology       0.470        -75.903605
                 0.350        -73.294387
Furniture        0.400        -73.259026
Technology       0.400        -71.713963
Furniture        0.300        -59.736982
Technology       0.450        -59.348554
                 0.370        -47.968005
Office Supplies  0.500        -47.252099
                 0.700        -45.139922
                 0.600        -39.844191
                 0.450        -28.211513
                 0.400        -21.041493
                 0.470        -20.016522
Technology       0.202        -14.518847
                 0.250        -11.530833
Office Supplies  0.270         -6.087113
Furniture        0.270         -3.719108
                 0.250         12.942917
Office Supplies  0.150         15.601811
                 0.200         16.143491
Furniture        0.200         19.035931
                 0.150         27.288298
Office Supplies  0.170         27.685866
                 0.000         31.689588
                 0.100         36.902682
Technology       0.200         51.619675
                 0.150         60.632834
                 0.300         65.207900
                 0.170         68.172717
                 0.100        102.479776
Furniture        0.100        102.765136
                 0.000        103.561601
Technology       0.002        125.762649
                 0.000        131.289033
                 0.070        140.565641
Furniture        0.070        141.488209
Name: profit, dtype: float64

In [109]:
df['sales'].sum()

np.int64(12642905)

In [110]:
df['profit'].sum()

np.float64(1469034.82128)

In [111]:
df['discount'].mean()

np.float64(0.14290754533047378)

In [112]:
df['order_id'].nunique()

25035

In [113]:
df.groupby('region')['sales'].sum().sort_values()

region
Canada              66932
Caribbean          324281
East               678834
West               725514
Central Asia       752839
Africa             783776
EMEA               806184
North Asia         848349
Southeast Asia     884438
Oceania           1100207
North             1248192
South             1600960
Central           2822399
Name: sales, dtype: int64

In [114]:
df.groupby('category')['profit_margin'].mean().sort_values()

category
Furniture          0.874818
Technology         4.965838
Office Supplies    5.855933
Name: profit_margin, dtype: float64

In [115]:
df.groupby('order_month')['sales'].sum()

order_month
1      675141
2      543768
3      770519
4      698603
5      904061
6     1269751
7      749423
8     1293852
9     1437432
10    1168220
11    1551319
12    1580816
Name: sales, dtype: int64

In [116]:
df.groupby('discount')['profit'].mean()

discount
0.000      61.039514
0.002     125.762649
0.070     140.990022
0.100      64.071216
0.150      50.602409
0.170      38.317107
0.200      23.552594
0.202     -14.518847
0.250       4.043371
0.270      -4.317213
0.300     -57.899557
0.320     -88.560656
0.350    -116.144693
0.370     -78.462191
0.400     -45.246603
0.402    -109.908138
0.450     -41.610973
0.470     -42.982420
0.500     -97.140158
0.550    -315.067200
0.570    -526.129000
0.600     -81.732147
0.602    -213.279085
0.650    -365.997971
0.700    -104.339576
0.800    -122.203244
0.850   -1534.329000
Name: profit, dtype: float64